name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      working-directory: ./cli
      run: docker build . --file Dockerfile --tag fdingler/go-hammer
    
    - name: Login to docker hub
      run: docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Publish image
      run: docker push fdingler/go-hammer
